/*
 * ViLE - Visual Library Engine
 * Copyright (c) 2010-2011, ViLE Team (team@vilevn.org)
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Widget graphics pack embedded into the binary (generated by
 * scripts/gen_vilepack.py - do not edit by hand).
 *
 * This is the original vilevn.pck from the upstream ViLE repository:
 * a ViLEPACK cabinet holding three PNG images used by the generic
 * widgets - button.png, checkbox.png and slider.png. The engine mounts
 * it in memory when no external vilevn.pck sits in the working
 * directory, so games no longer need to carry the file.
 */

#ifndef _VILEPACK_H_
#define _VILEPACK_H_

//! Raw ViLEPACK cabinet with the widget graphics
extern const unsigned char VILE_PACK_DATA[];
//! Size of VILE_PACK_DATA in bytes
extern const unsigned int VILE_PACK_SIZE;

#endif
